### ISSUE TITLE
draw a element can set a id or class?

### ISSUE THREAD

**Issue by touchmii** [jfree/jfreesvg#47]
like this, can help web identify element name.

<g id="head"> <path id="beak" d="M50.43,68.52c0,0-8.81,2.58-10.93,4.86l9.12,9.87C48.61,83.24,48.76,74.28,50.43,68.52"/> <path class="eye-ball" d="M60.53,71.68c0-6.33,5.13-11.46,11.46-11.46c6.33,0,11.46,5.13,11.46,11.46c0,6.33-5.13,11.46-11.46,11.46 C65.66,83.14,60.53,78.01,60.53,71.68"/>

**Comment by jfree** [comment]
This would be better in [Discussions](https://github.com/jfree/jfreesvg/discussions).

Anyway, setting the id for an element is supported.  Since JFreeSVG targets the Graphics2D API, it makes use of the rendering hints facility (slightly non-obvious, but it has the advantage that your code will still run against other Graphics2D implementations - the hints get ignored, but otherwise the rendering is the same).  You can do something like this:

```
Graphics2D g2 = ... (from wherever you create your Graphics2D instance)
g2.setRenderingHint(SVGHints.KEY_ELEMENT_ID, "XYZ");
g2.fill(new Rectangle2D.Double(1.0, 2.0, 3.0, 4.0));
```

...and then the rectangle in the SVG output will be tagged with the specified element ID.
